-- Optional: the same tables Hibernate creates automatically (spring.jpa.hibernate.ddl-auto=update).
-- Run this yourself only if you prefer to create the tables manually (then set ddl-auto=validate).

CREATE TABLE IF NOT EXISTS users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(100) NOT NULL,
    email    VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL          -- BCrypt hash (60 chars), never the raw password
);

CREATE TABLE IF NOT EXISTS expenses (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount   NUMERIC(12,2) NOT NULL,
    date     DATE          NOT NULL,
    category VARCHAR(50)   NOT NULL,
    note     VARCHAR(60),
    user_id  BIGINT        NOT NULL REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_expenses_user_id ON expenses(user_id);
